FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY Ecomeal.client/Ecomeal.client/ Ecomeal.client/
RUN dotnet workload restore Ecomeal.client/Ecomeal.client/Ecomeal.client.csproj || true
RUN dotnet publish Ecomeal.client/Ecomeal.client/Ecomeal.client.csproj -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /app .
ENV ASPNETCORE_HTTP_PORTS=8080
EXPOSE 8080
ENTRYPOINT ["dotnet", "Ecomeal.client.dll"]
